-- Roadmap · sync ao vivo via Supabase
-- Fase 1: schema + RLS + seed de hipóteses
-- Gerado em 2026-08-27. Fórmula única de % = Done/total (aplicada na Edge Function).

-- ── Snapshot de status do Jira ───────────────────────────────────────────────
-- Guarda APENAS o mapa de status por issue: { "FRONT-123": {"status":"Done","blocked":false}, ... }.
-- A estrutura (épicos, descrições, agrupamentos, tracks) continua no código; o
-- front sobrepõe este mapa e calcula % = Done/total num único lugar (acaba a divergência).
create table if not exists public.roadmap_snapshot (
  id         uuid        primary key default gen_random_uuid(),
  statuses   jsonb       not null default '{}'::jsonb,   -- { key: { status, blocked } }
  summary    jsonb       not null default '{}'::jsonb,   -- contadores do sync (done/ip/todo/blocked/total)
  synced_at  timestamptz not null default now(),
  synced_by  text
);
comment on table public.roadmap_snapshot is 'Último sync do Jira (mapa de status). A app lê o registro mais recente: order by synced_at desc limit 1.';

-- ── Hipóteses (independente do Jira, editável) ───────────────────────────────
create table if not exists public.hypotheses (
  id           text        primary key,
  title        text        not null,
  description  text        not null default '',
  type         text[]      not null default '{}',        -- tracks: migracao | evolucao | cdp
  status       text        not null default 'a-avaliar', -- backlog | a-avaliar | planejado
  previsao     text,
  cliente_tags text[],
  subitems     text[],
  sort_order   int         not null default 0,
  updated_at   timestamptz not null default now()
);

-- ── RLS ──────────────────────────────────────────────────────────────────────
alter table public.roadmap_snapshot enable row level security;
alter table public.hypotheses       enable row level security;

-- leitura pública (o roadmap é de leitura para quem acessa)
drop policy if exists roadmap_snapshot_read on public.roadmap_snapshot;
create policy roadmap_snapshot_read on public.roadmap_snapshot for select using (true);

drop policy if exists hypotheses_read on public.hypotheses;
create policy hypotheses_read on public.hypotheses for select using (true);

-- Escrita de hipóteses: NÃO há policy de escrita para o navegador (app sem login).
-- → visitantes só leem; a edição é feita pelo Supabase Table Editor (dashboard usa
--   service_role, que ignora RLS). Assim ninguém pela URL pública altera as hipóteses.
-- roadmap_snapshot também não tem policy de escrita → só a Edge Function (service_role) grava.
drop policy if exists hypotheses_write on public.hypotheses;

-- ── Seed das hipóteses (idempotente) ─────────────────────────────────────────
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h1', 'Expansão dos Critérios do Segmentador', 'Novos critérios de segmentação para enriquecer a construção de audiências.', array['migracao','evolucao','cdp']::text[], 'a-avaliar', null, null, array['LTV','Ticket médio','Produtos comprados','UF','Produtos visualizados','Categorias visualizadas','Forma de pagamento','Canal da compra (loja física ou e-commerce)']::text[], 0) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h2', 'IP Dedicado para E-mail', 'Infraestrutura de envio de e-mail com IP dedicado, garantindo maior reputação e entregabilidade para os disparos da plataforma.', array['evolucao']::text[], 'planejado', 'Final de setembro', null, null, 1) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h3', 'Nova página de perfil de clientes', 'Refatoração da tela de visão única de cliente trazendo mais dados relativos ao pedido, como forma de pagamento, entrega etc.', array['migracao','evolucao','cdp']::text[], 'planejado', 'Final de setembro', null, null, 2) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h4', 'Integração com ERPs — Loja Física', 'Integração nativa com ERPs de varejo para captura e envio automático de dados de loja física diretamente para a CDP da Wake Experience 2.0. Para clientes com outros sistemas, também será disponibilizada uma API aberta.', array['evolucao']::text[], 'a-avaliar', null, null, array['LINX Microvix','LINX POS','TOTVS Moda']::text[], 3) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h5', 'API de Consulta de Dados da CDP', 'API para consulta de dados diretamente na CDP da Wake Experience 2.0, permitindo que sistemas externos acessem o perfil unificado dos clientes de forma programática.', array['evolucao','cdp']::text[], 'a-avaliar', null, array['Ybera','Shoulder']::text[], array['Consulta de dados de clientes e atributos armazenados na CDP','Integração com sistemas externos como CRMs, ERPs e ferramentas de BI','Acesso via autenticação segura por token']::text[], 4) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h6', 'Envios comportamentais', 'A partir do comportamento do cliente são enviados os produtos com que ele interagiu + recomendações baseadas em inteligência.', array['migracao']::text[], 'a-avaliar', null, null, array['Abandonou o Carrinho e Não Comprou Nada','Abandonou o Carrinho e Não Levou o Item','Aniversário','Assinou a Newsletter','Avise-me','Buscou um Produto e Não Comprou','Clientes que nunca compraram','Decididos: Visitou o Mesmo Produto Várias Vezes','Deixou de Acessar o Site por 7 Dias','Fidelidade: Clientes fiéis','Inativos: Parou de Abrir Campanhas','Indecisos: Navegou em Vários Produtos sem Comprar','Navegou na Última Hora','Navegou na Última Semana','Navegou no Último Mês','Novidades na Lista de Desejos','Novidades: Novos Produtos na Loja','Novos Cadastros','Pessoas ativas: Acessou o Site nos Últimos 120 Dias','Pessoas engajadas: Acessou o Site nos Últimos 7 Dias','Pessoas inativas: Deixou de Acessar o Site por 120 Dias','Pessoas que compraram há 7 dias','Pós Compra','Reconquista: parou de comprar','Recorrência: Comprou um Produto de Uso Contínuo','Redução de Preços Similares: Navegou em uma Categoria que Baixou de Preço','Redução de Preços: Visualizou um Produto que Baixou de Preço','Tendências: Navegou em uma Categoria com Produtos em Alta']::text[], 5) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h7', 'Relatórios de Performance', 'Conjunto completo de relatórios para acompanhamento da performance das comunicações enviadas pela plataforma.', array['migracao']::text[], 'a-avaliar', null, null, array['Relatórios de Envio — e-mail, WhatsApp, SMS, Push, Web Push, App Push, On-site, Lightbox e Repiques','Relatórios de Interação — ranking de assuntos, fidelidade de abertura, Teste A/B','Relatórios Transacionais — Workflow e API','Relatório de Performance Geral — receita gerada pelas campanhas','Relatório de Performance de Envios Automáticos — réguas automáticas ativas','Reputação de Provedores — Gmail, Hotmail','Relatório de On-site e Web Push — métricas por campanha']::text[], 6) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h8', 'SMS', 'Novo canal de envio via SMS, permitindo disparos pontuais e automáticos para a base de clientes.', array['migracao']::text[], 'a-avaliar', null, null, null, 7) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h9', 'Wake U — Agenda do Vendedor', 'Sistema de oportunidades de venda direcionadas ao time de loja física, permitindo contatos ativos com clientes com base em dados da CDP — como aniversariantes, clientes inativos ou compradores recentes.', array['migracao']::text[], 'a-avaliar', null, null, null, 8) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h10', 'Matriz RFV (RFM)', 'Segmentação automática da base de clientes com base nos critérios de Recência, Frequência e Valor de compra, identificando perfis mais valiosos e criando estratégias personalizadas para cada grupo.', array['migracao']::text[], 'a-avaliar', null, null, null, 9) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h11', 'Gestão de Pressão de Comunicação', 'Controle de frequência de comunicação por cliente, evitando excesso de contatos e melhorando a experiência do usuário final.', array['migracao']::text[], 'a-avaliar', null, null, null, 10) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h12', 'Teste A/B', 'Criação e análise de testes de variação para campanhas e conteúdos, permitindo otimizar assuntos, templates e audiências.', array['migracao']::text[], 'a-avaliar', null, null, null, 11) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h13', 'Envios Transacionais', 'Disparos automáticos de e-mail e WhatsApp baseados em eventos transacionais, como confirmação de pedido, nota fiscal e atualizações de status.', array['migracao']::text[], 'a-avaliar', null, null, null, 12) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h14', 'Web Push', 'Notificações push no navegador para engajamento de clientes mesmo fora do site, sem necessidade de app instalado.', array['migracao']::text[], 'a-avaliar', null, null, null, 13) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h15', 'E-mail Inteligente', 'Templates de e-mail com personalização dinâmica baseada em IA, adaptando conteúdo e recomendações ao perfil de cada cliente.', array['migracao']::text[], 'a-avaliar', null, null, null, 14) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h16', 'Workflow', 'Criação de jornadas de comunicação automatizadas e multicanal, baseadas no engajamento e comportamento do usuário.', array['migracao']::text[], 'a-avaliar', null, null, array['Criação de jornadas com múltiplos passos, canais e condições','Gatilhos baseados em comportamento e engajamento do usuário (abertura, clique, compra, etc.)','Ramificações condicionais para personalização da jornada por perfil de resposta','Suporte a e-mail e WhatsApp na mesma jornada']::text[], 15) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h17', 'App Push', 'Novo canal de notificação via push em aplicativos mobile, permitindo disparos pontuais e automáticos diretamente para o app da loja.', array['migracao']::text[], 'a-avaliar', null, null, null, 16) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h24', 'Novos Filtros na Tela de Visão de Clientes', 'Evolução da tela de visão de clientes com novos critérios de filtragem, permitindo que o usuário faça combinações mais precisas para segmentar e analisar sua base diretamente na tela.', array['evolucao','cdp']::text[], 'a-avaliar', null, null, array['Filtro por ticket médio','Filtro por LTV','Filtro por audiência']::text[], 17) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h23', 'Córtex para Segmentos', 'Refinamento e finalização do Córtex aplicado ao Segmentador, atualmente implementado com dados mocados. Inclui a evolução da inteligência do Córtex para enriquecer segmentos com dados reais e ampliar suas capacidades analíticas.', array['evolucao','cdp']::text[], 'a-avaliar', null, null, array['Substituição dos dados mocados por dados reais na integração com o Córtex','Refinamento da experiência e dos resultados gerados pelo Córtex no Segmentador','Evolução das capacidades analíticas do Córtex para segmentos']::text[], 18) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h22', 'Receita e exportações CSV nas campanhas', 'Concluir a disponibilização de receita por campanha e as exportações de relatórios CSV (envios pontuais, automáticos e segmentos) via central de notificações.', array['migracao']::text[], 'planejado', null, null, array['Receita por campanha disponível nos relatórios','Exportação CSV de envios pontuais','Exportação CSV de envios automáticos','Exportação CSV de segmentos','Distribuição via central de notificações']::text[], 19) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h21', 'Adaptação do SDK para Aplicativos Mobile', 'Desenvolvimento e adaptação do SDK para instalação em aplicativos mobile, permitindo que clientes que operam com app próprio possam capturar navegação, eventos e dados dos seus clientes diretamente do aplicativo e enviá-los à CDP da Wake Experience 2.0.', array['evolucao','cdp']::text[], 'a-avaliar', null, null, array['SDK compatível com aplicativos mobile (iOS e Android)','Captura de eventos de navegação e comportamento dentro do app','Envio de dados de clientes do app para a CDP','Unificação do perfil do cliente entre web e app']::text[], 20) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h20', 'Relatório de Segmento', 'Área dedicada dentro do Segmentador para visualização detalhada de qualquer segmento — predefinido ou criado pelo usuário. Permite monitorar o tamanho da audiência, sua evolução ao longo do tempo e quem são os clientes dentro daquele segmento.', array['evolucao']::text[], 'a-avaliar', null, null, array['Visão do total de pessoas dentro de um segmento','Evolução histórica do segmento (crescimento ou queda)','Lista de clientes que compõem o segmento','Suporte a segmentos predefinidos e segmentos criados pelo usuário']::text[], 21) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h19', 'Captação de Device e Sistema Operacional pelo SDK', 'O SDK deve captar e armazenar o device e sistema operacional do cliente, tornando esse dado um critério segmentável e visível no perfil de cada cliente. Permite saber de onde a compra veio e onde ele navegou, habilitando promoções e condições de pagamento específicas por canal e sistema operacional.', array['evolucao','cdp']::text[], 'a-avaliar', null, array['Ybera']::text[], array['Captação de device (mobile, desktop, tablet) e sistema operacional via SDK','Dado disponível como critério de segmentação no Segmentador','Exibição no perfil único do cliente (canal de navegação e canal de compra)','Viabilizar promoções e condições de pagamento específicas por canal e SO']::text[], 22) on conflict (id) do nothing;
insert into public.hypotheses (id, title, description, type, status, previsao, cliente_tags, subitems, sort_order) values ('h18', 'Acesso Independente de Plataforma de E-commerce', 'Foco será em Wake Commerce. Clientes com outras plataformas (VTEX, Shopify, Magento) poderiam utilizar a plataforma de forma independente, sem necessidade de vínculo com o Wake Commerce.', array['evolucao']::text[], 'a-avaliar', null, null, array['Cadastro e acesso à plataforma sem integração com Wake Commerce','Compatibilidade com as principais plataformas de e-commerce do mercado','Mesmas funcionalidades disponíveis para todos os clientes, independente da plataforma utilizada']::text[], 23) on conflict (id) do nothing;
